export const ActionTypes = {
    SET_SIDEBAR : "SET_SIDEBAR",
    SET_LOGIN_USER:"SET_LOGIN_USER",
    REMOVE_LOGIN_USER:"REMOVE_LOGIN_USER",
    ADD_AUTHTOKEN: "ADD_AUTHTOKEN",
    REMOVE_AUTHTOKEN: "REMOVE_AUTHTOKEN",
    LOGIN_INFO:"LOGIN_INFO"
}
